In [64]:
d1 = "jazz music has a swing rhythm"
d2 = "swing is hard to explain"
d3 = "swing rhythm is a natural rhythm"

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
count_vect = CountVectorizer(stop_words='english')
X_train_counts = count_vect.fit_transform([d1,d2,d3])
print(count_vect.get_feature_names())
print(X_train_counts.todense())

['explain', 'hard', 'jazz', 'music', 'natural', 'rhythm', 'swing']
[[0 0 1 1 0 1 1]
 [1 1 0 0 0 0 1]
 [0 0 0 0 1 2 1]]


In [67]:
print(X_train_counts)

  (0, 5)	1
  (0, 6)	1
  (0, 3)	1
  (0, 2)	1
  (1, 0)	1
  (1, 1)	1
  (1, 6)	1
  (2, 4)	1
  (2, 5)	2
  (2, 6)	1


In [68]:
from sklearn.feature_extraction.text import TfidfTransformer

In [69]:
tf_transformer = TfidfTransformer(use_idf=False, norm='l1')
X_train_tf= tf_transformer.transform(X_train_counts)
print(X_train_tf.todense())

[[ 0.          0.          0.25        0.25        0.          0.25        0.25      ]
 [ 0.33333333  0.33333333  0.          0.          0.          0.
   0.33333333]
 [ 0.          0.          0.          0.          0.25        0.5         0.25      ]]


In [70]:
from sklearn.tree import DecisionTreeClassifier

In [78]:
X = X_train_tf
y = [1,0,1]
model = DecisionTreeClassifier(max_depth=5)
model.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [79]:
from sklearn.metrics import accuracy_score
accuracy_score(y,model.predict(X))

1.0

In [80]:
from sklearn.linear_model import LogisticRegression

In [81]:
model2 = LogisticRegression()
model2.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [82]:
accuracy_score(y,model2.predict(X))

0.66666666666666663

In [83]:
from matplotlib.pylab import plt
%matplotlib inline